### PR TITLE
Do not always force upgrade for master builds

### PR DESCRIPTION
**Pull request by fbladilo**
- Handle master special upgrade/redeploy case properly
- Added conditional to check for supplied master DB schema and compare against DB
- If both schemas are identical, proceed with redeploy, if master image schema is newer, proceed with upgrade

### CODE REVIEW

**Comment by fbladilo** [comment]
@bazulay Please review, fixes #93

**Comment by bazulay** [comment]
LGMT

bu I would like @carbonin  to make sure the logic we used (examining the db migration files) is actually correct.

**Comment by fbladilo** [comment]
@carbonin Definitely looks like a much better fit :smile:  So check for pending, if found, then migrate/upgrade. I was not aware of that rake task, Thanks.

**Comment by fbladilo** [comment]
@carbonin @bazulay Please see latest commit using suggested rake task, tested on OCP 3.4 for both cases.

**Comment by bazulay** [comment]
LGTM

**Pull request merged**
