### PR TITLE
[FINE] Randomize DB password by default and store on secret

### LINKED ISSUE #105: PostgreSQL Password should be Autogenerated
Current ability of configuring a password for PostgreSQL (`DATABASE_PASSWORD`) is handy but in case it's not defined it shouldn't be a known default password `smarvm` but rather a random generated one (and stored as a secret).
IIRC password generation is well supported and easy to use in Kubernetes/OpenShift (for inspiration you can look at Heapster/Hawkular).

cc @fbladilo @bazulay

### PR DESCRIPTION
**Pull request by gregswift**
Cherry-picked from master. credit to @fbladilo in #118 

- Create secret template object along with necessary keys
- Randomize DB password template parameter
- Expose DB password secret as a ENV variable for deployment use
- Fixes #105

### CODE REVIEW

**Comment by Fryguy** [comment]
I'm surprised the bot didn't mark this as a fine PR

/me goes to check what's up with @miq-bot

**Comment by Fryguy** [comment]
Oh wow...the bot was never enabled on this repo 😮

**Comment by carbonin** [comment]
@gregswift is this a clean cherry-pick from #118 ?

If so we can just label that PR as `fine-yes` and @simaishi will backport it before we cut the next release.

**Comment by gregswift** [comment]
@carbonin it is a clean cherry-pick.

**Comment by carbonin** [comment]
Okay, I added the tag on the original PR and will go ahead and close this.

**Pull request closed without merging**
