### PR TITLE
[HAMMER] [hammer only] Podify openidc hammer

### PR DESCRIPTION
**Pull request by jvlcek**
**Note**: This is a **_hammer only_** PR

This is the hammer version of the updates made to master in [PR 251](https://github.com/ManageIQ/manageiq-pods/pull/251)

### CODE REVIEW

**Comment by jvlcek** [comment]
@abellotti Please review.

I've tested on OpenShift

**Comment by carbonin** [comment]
Why is there a HAMMER specific PR for this? Looks like it would be a clean cherry-pick as it doesn't change the images. @simaishi, what do you think?

**Comment by simaishi** [comment]
Yeah.. if the change is identical, we should use the master PR (plus README which exists in this PR but doesn't in master PR).

**Comment by jvlcek** [comment]
Running the below commands show a differences:

mac% git diff hammer master templates/miq-template-ext-db.yaml
and
mac% git diff hammer master templates/miq-template.yaml

**Comment by simaishi** [comment]
@jvlcek Even if the files are not identical, the changes can still be cherry-picked. This will be a clean cherry-pick, but I can also resolve minor conflicts while backporting if needed. What really matters is if the exact same diff can go to different branches.

**Comment by jvlcek** [comment]
Thank you @simaishi ! I needed this change staged in a branch so I could build hammer based docker images for my testing. So I thought I'd be making it easier my posting this PR. I'll close this it it's easier for you to simply cherry pick https://github.com/ManageIQ/manageiq-pods/pull/251

**Pull request closed without merging**
