### PR TITLE
Parametize APPLICATION_REPLICA_COUNT for petset controller

### PR DESCRIPTION
**Pull request by fbladilo**
- Allow user to deploy desired number of MIQ replicas using parameters

### CODE REVIEW

**Comment by fbladilo** [comment]
@bazulay @simaishi Please review..

**Comment by bazulay** [comment]
@fbladilo 
Since I have never tried it ....
How does it work ? the replica is increased after the previous replica is ready ?
Otherwise it may create a race of writing region data  the region_pv

**Comment by fbladilo** [comment]
@bazulay Correct, statefulsets scale orderly, only the previous replica is online/ready the next one starts.

**Comment by bazulay** [comment]
LGMT

**Pull request merged**
