### PR TITLE
Fix the external db template after merging #207

### PR DESCRIPTION
**Pull request by carbonin**
Missed these in #207

### CODE REVIEW

**Comment by bdunne** [comment]
Can you sync up the two templates?  There are other things that are not the same.  It's hard to compare in a diff viewer

**Comment by carbonin** [comment]
Yeah, noticed that too @bdunne. Wasn't sure if I should do that as a separate PR or a separate commit in this one.

**Comment by bdunne** [comment]
Yeah, multiple commits in one PR would probably be best.

**Comment by carbonin** [comment]
Expanded the scope of this PR to include other miscellaneous fixes to the templates caused by the previous changes.

Now you should be able to `diff` the two templates and only see database-related objects

**Comment by carbonin** [comment]
Also because I reordered the object list reviewing commit-by-commit is strongly recommended :smile:

**Pull request merged**
