### PR TITLE
[HAMMER] Move from apache module mod_auth_kerb to mod_auth_gssap

### PR DESCRIPTION
**Pull request by jvlcek**
https://www.pivotaltracker.com/n/projects/1610127/stories/160297262

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650583

This PR is one of two that will implement moving external authentication support from
the Apache module mod_auth_kerb to mod_auth_gssapi for the Openshift/podified build

The other PR is:
https://github.com/ManageIQ/container-httpd/pull/38

### CODE REVIEW

**Comment by jvlcek** [comment]
This is the Hammer specific PR

**Comment by jvlcek** [comment]
@miq-bot add_label enhancement

**Comment by jvlcek** [comment]
@miq-bot assign @abellotti

**Comment by jvlcek** [comment]
This is the Hammer specific PR

**Comment by carbonin** [comment]
This looks like it might backport cleanly, are you sure you need a hammer specific PR?

**Comment by jvlcek** [comment]
Although this ManageIQ/manageiq-pods#314 may cleanly cherry-pick to hammer, because the templates are so different between master and hammer I went ahead and created the hammer specific PR here: ManageIQ/manageiq-pods#313. Just to be ready in case is doesn't cleanly cherry-pick

**Comment by simaishi** [comment]
https://github.com/ManageIQ/manageiq-pods/pull/314 was a clean cherry-pick.

**Pull request closed without merging**
