### PR TITLE
Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472

### PR DESCRIPTION
**Pull request by bdunne**
Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472

### CODE REVIEW

**Comment by Fryguy** [comment]
@bdunne A conflict occurred during the backport of this pull request to `morphy`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `morphy` branch in order to resolve this.

Conflict details:

```diff
diff --cc .travis.yml
index c1d723c,309b707..0000000
--- a/.travis.yml
+++ b/.travis.yml
@@@ -13,6 -13,6 +13,12 @@@ cache
    - "$HOME/gopath/pkg/mod"
  before_script:
  - eval "$(gimme 1.14)"
++<<<<<<< HEAD
 +- travis_wait curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.17.2/operator-sdk-v0.17.2-$(uname -m)-linux-gnu -o /home/travis/bin/operator-sdk && chmod +x /home/travis/bin/operator-sdk
 +script:
 +- bundle exec rspec
++=======
+ - travis_wait curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.17.2/operator-sdk-v0.17.2-$(uname
+   -m)-linux-gnu -o /home/travis/bin/operator-sdk && chmod +x /home/travis/bin/operator-sdk
+ dist: bionic
++>>>>>>> ecbb568... Merge pull request #757 from bdunne/update_travis_dist
```

**Comment by Fryguy** [comment]
@bdunne A conflict occurred during the backport of this pull request to `lasker`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `lasker` branch in order to resolve this.

Conflict details:

```diff
diff --cc .travis.yml
index e9cbde7,309b707..0000000
--- a/.travis.yml
+++ b/.travis.yml
@@@ -12,7 -13,6 +12,13 @@@ cache
    - "$HOME/gopath/pkg/mod"
  before_script:
  - eval "$(gimme 1.14)"
++<<<<<<< HEAD
 +- travis_wait curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.15.1/operator-sdk-v0.15.1-$(uname
 +  -m)-linux-gnu -o /home/travis/bin/operator-sdk && chmod +x /home/travis/bin/operator-sdk
 +script:
 +- bundle exec rspec
++=======
+ - travis_wait curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.17.2/operator-sdk-v0.17.2-$(uname
+   -m)-linux-gnu -o /home/travis/bin/operator-sdk && chmod +x /home/travis/bin/operator-sdk
+ dist: bionic
++>>>>>>> ecbb568... Merge pull request #757 from bdunne/update_travis_dist
```

**Comment by bdunne** [comment]
https://github.com/ManageIQ/manageiq-pods/pull/760

**Comment by Fryguy** [comment]
Backported to `morphy` via #760 
Backported to `lasker` via #761

**Comment by Fryguy** [comment]
@bdunne A conflict occurred during the backport of this pull request to `kasparov`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `kasparov` branch in order to resolve this.

Conflict details:

```diff
diff --cc .travis.yml
index 27856d2,309b707..0000000
--- a/.travis.yml
+++ b/.travis.yml
@@@ -12,6 -13,6 +12,12 @@@ cache
    - "$HOME/gopath/pkg/mod"
  before_script:
  - eval "$(gimme 1.14)"
++<<<<<<< HEAD
 +- travis_wait curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.15.1/operator-sdk-v0.15.1-$(uname -m)-linux-gnu -o /home/travis/bin/operator-sdk && chmod +x /home/travis/bin/operator-sdk
 +script:
 +- bundle exec rspec
++=======
+ - travis_wait curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.17.2/operator-sdk-v0.17.2-$(uname
+   -m)-linux-gnu -o /home/travis/bin/operator-sdk && chmod +x /home/travis/bin/operator-sdk
+ dist: bionic
++>>>>>>> ecbb568... Merge pull request #757 from bdunne/update_travis_dist
```

**Comment by bdunne** [comment]
Kasparov backport PR: https://github.com/ManageIQ/manageiq-pods/pull/762

**Pull request merged**
