### PR TITLE
[WIP] Move certificates from /root to /etc/pki/tls/

### PR DESCRIPTION
**Pull request by bdunne**
Requires: https://github.com/ManageIQ/container-postgresql/pull/32

Based on discussion in: https://github.com/ManageIQ/manageiq/pull/21527#discussion_r740367755

### CODE REVIEW

**Comment by kbrock** [comment]
thanks for putting this together.
Is there anything I can do to help with this?

**Comment by kbrock** [comment]
@bdunne darn. Could this be redirected?

I guess my main desire for this was to have the credentials available for non-root users on the appliance. So this would be more of a consistency thing.

You thinking punt is better?

**Comment by kbrock** [comment]
Is this still viable?

**Comment by agrare** [comment]
:+1: this is a great idea, wonder if we could do the same on appliances (move to a more standard location)

**Pull request closed without merging**
