### PR TITLE
MIQ app Dockerfile fix bower relocation

### PR DESCRIPTION
**Pull request by fbladilo**
- See https://github.com/ManageIQ/manageiq/pull/14536

### CODE REVIEW

**Comment by fbladilo** [comment]
@simaishi @bazulay We need these changes on miq-pod , monolithic already taken care of by original PR.

**Comment by bazulay** [comment]
LGTM

**Comment by simaishi** [comment]
LGTM.  Removing `fine/yes` as https://github.com/ManageIQ/manageiq/pull/14536 is 'master' only change.

**Comment by bazulay** [comment]
@simaishi  good catch ... label was my bad

**Pull request merged**
