### PR TITLE
Switch to latest since v0.0.1 tag doesn't exist yet

### PR DESCRIPTION
**Pull request by bdunne**
Pull always since we're using the latest tag which is not static

### CODE REVIEW

**Comment by carbonin** [comment]
I think we probably need a jansa-specific PR to keep this "IfNotPresent" and `latest-jansa` for that branch.

**Comment by carbonin** [comment]
Or maybe wait until we have an actually released jansa branch?

I'm not really sure what to do for this.

**Comment by bdunne** [comment]
I think the pull policy needs to reflect the tag.  If it's a moving tag (latest), the pull policy should be `Always`.  Once we have a static release tag, the pull policy should be `IfNotPresent`

**Comment by carbonin** [comment]
Okay, this looks good to me then. I'll set jansa/no just to make sure we do something different there.

**Comment by Fryguy** [comment]
Marking this as backported since techically the change came over, just in a different form

**Pull request merged**
