### PR TITLE
Move to CentOS Stream

### PR DESCRIPTION
**Pull request by Fryguy**
Part of https://github.com/ManageIQ/manageiq-appliance-build/issues/459

@bdunne Please review

### CODE REVIEW

**Comment by Fryguy** [comment]
I was able to build the base image locally but it failed on the operator build for me.  @bdunne Can you verify this builds properly?

**Review by bdunne — APPROVED** [review]
Build looks good to me

**Comment by Fryguy** [comment]
`morphy` backport details:

```
commit 364f96ceb57e6982d9a3d415f22df0063f098467 (HEAD -> morphy, upstream/morphy)
Author: Brandon Dunne <bdunne@redhat.com>
Date:   Fri Jun 11 12:11:09 2021 -0400

    Merge pull request #725 from Fryguy/centos_stream

    Move to CentOS Stream

    (cherry picked from commit 6615d87a008de3878c92b1cbf3f159100a3a8b50)
```

**Comment by Fryguy** [comment]
Backported to `lasker` in commit 3fc41a7679a3605acb5bd59496042026b13c0491.

```text
commit 3fc41a7679a3605acb5bd59496042026b13c0491
Author: Brandon Dunne <bdunne@redhat.com>
Date:   Fri Jun 11 12:11:09 2021 -0400

    Merge pull request #725 from Fryguy/centos_stream
    
    Move to CentOS Stream
    
    (cherry picked from commit 6615d87a008de3878c92b1cbf3f159100a3a8b50)
```

**Pull request merged**
