### PR TITLE
[WIP] Kafka/Zookeeper SSL

### PR DESCRIPTION
**Pull request by nasark**
Opening a WIP PR to collaborate and get some more eyes on this for troubleshooting purposes. 

Notes:
- At the moment I am focusing on getting SSL working with only the Kafka client and will focus on Zookeeper afterwards
- I've left commented code to show the various configurations that I have attempted using
- `addKafkaStores` and `addZookeeperStores` will be integrated to `addInternalCertificate` method 
- I generated the truststore and keystores using the root CA generated by the `cert-generator` script

Resources/docs used:
- https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#security
- https://github.com/bitnami/containers/tree/main/bitnami/zookeeper#configuration
- https://github.com/confluentinc/confluent-platform-security-tools/blob/master/single-trust-store-diagram.pdf

@miq-bot assign @bdunne 
@miq-bot add_reviewers @agrare

### CODE REVIEW

**Comment by nasark** [comment]
I am currently facing an issue where the `KafkaServer` SASL credentials are missing from the JAAS config file:
 ```
[2023-03-07 15:59:41,359] INFO [feature-zk-node-event-process-thread]: Starting (kafka.server.FinalizedFeatureChangeListener$ChangeNotificationProcessorThread)
[2023-03-07 15:59:41,374] INFO Feature ZK node at path: /feature does not exist (kafka.server.FinalizedFeatureChangeListener)
[2023-03-07 15:59:41,384] ERROR [KafkaServer id=1004] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.IllegalArgumentException: Could not find a 'KafkaServer' or 'sasl_ssl.KafkaServer' entry in the JAAS configuration. System property 'java.security.auth.login.config' is /opt/bitnami/kafka/config/kafka_jaas.conf
	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:131)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:96)
	at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:69)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:168)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at kafka.server.BrokerToControllerChannelManagerImpl.newRequestThread(BrokerToControllerChannelManager.scala:188)
	at kafka.server.BrokerToControllerChannelManagerImpl.<init>(BrokerToControllerChannelManager.scala:167)
	at kafka.server.BrokerToControllerChannelManager$.apply(BrokerToControllerChannelManager.scala:133)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:286)
	at kafka.Kafka$.main(Kafka.scala:109)
	at kafka.Kafka.main(Kafka.scala)
 ```


The `KafkaClient` credentials are set using `KAFKA_CLIENT_*` env vars but not sure how the server equivalent are to be set

 Logs:
[kafka.log](https://github.com/ManageIQ/manageiq-pods/files/10912051/kafka.log)
[zookeeper.log](https://github.com/ManageIQ/manageiq-pods/files/10912054/zookeeper.log)

**Comment by agrare** [comment]
Not sure if you've found this already but looks like KAFKA_OPTS has to be set, https://docs.confluent.io/platform/current/kafka/authentication_sasl/index.html#alternative-jaas-configuration

**Comment by nasark** [comment]
> Not sure if you've found this already but looks like KAFKA_OPTS has to be set, https://docs.confluent.io/platform/current/kafka/authentication_sasl/index.html#alternative-jaas-configuration
> 
> (I see you have that already but commented out so maybe it didn't work)

Yeah I had tried that and it didn't seem to make a difference as I got the same error. I also see from the error logs that `java.security.auth.login.config` is being set anyway which is what the KAFKA_OPTS would have done:
 
```
java.lang.IllegalArgumentException: Could not find a 'KafkaServer' or 'sasl_ssl.KafkaServer' entry in the JAAS configuration. System property 'java.security.auth.login.config' is /opt/bitnami/kafka/config/kafka_jaas.conf
```

**Comment by nasark** [comment]
Update: I was able to add KafkaServer sasl_jaas_config but now hitting the following:
```
[2023-03-08 18:57:43,937] INFO [feature-zk-node-event-process-thread]: Starting (kafka.server.FinalizedFeatureChangeListener$ChangeNotificationProcessorThread)
[2023-03-08 18:57:43,955] INFO Feature ZK node at path: /feature does not exist (kafka.server.FinalizedFeatureChangeListener)
[2023-03-08 18:57:43,965] ERROR [KafkaServer id=1002] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.IllegalArgumentException: Login module control flag is not available in the JAAS config
	at org.apache.kafka.common.security.JaasConfig.loginModuleControlFlag(JaasConfig.java:85)
	at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:111)
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:88)
	at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:69)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:168)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at kafka.server.BrokerToControllerChannelManagerImpl.newRequestThread(BrokerToControllerChannelManager.scala:188)
	at kafka.server.BrokerToControllerChannelManagerImpl.<init>(BrokerToControllerChannelManager.scala:167)
	at kafka.server.BrokerToControllerChannelManager$.apply(BrokerToControllerChannelManager.scala:133)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:286)
	at kafka.Kafka$.main(Kafka.scala:109)
	at kafka.Kafka.main(Kafka.scala)
```

it may be due to syntactical errors in the jaas config?

**Comment by nasark** [comment]
> Do we still need zookeeper? I recall keenan saying it was no longer necessary? That would simplify this quite a bit.

It is being worked on. The recent commit was to save the config that has Kafka up and running with SASL_SSL

**Comment by nasark** [comment]
Closing as this was opened for debug/collaboration purposes as well as the reasoning that we are no longer moving forward with Zookeeper since KRaft works

**Pull request closed without merging**
