### PR TITLE
Added olm files

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes part of https://github.com/ManageIQ/manageiq-pods/issues/415

**Special notes for your reviewer**:

Those files are generated by command as follows:

```
operator-sdk generate csv --csv-version 0.0.1 --update-crds
```

FYI @carbonin @Fryguy

### CODE REVIEW

**Comment by chessbyte** [comment]
Should we ensure that ManageIQ is the name in these files as we are doing [here](https://github.com/ManageIQ/manageiq-pods/pull/444)?

**Comment by chessbyte** [comment]
For anybody interested, here is a link to the [OLM Book](https://operator-framework.github.io/olm-book/)

**Comment by gyliu513** [comment]
Thanks Oleg @chessbyte , let me update this PR after the rename work got merged.

**Comment by carbonin** [comment]
Does this mean that the CRD and operator deployment are duplicated? Is there a way to not duplicate them? Or maybe we should check that they have both been generated correctly as a part of the CI tests? @Fryguy ?

**Comment by gyliu513** [comment]
The OLM will be committed to https://github.com/operator-framework/community-operators later, and it will be available in operatorhub.io

But for the CRD and deployment files, the dev can still use them for local deployment and test.

**Comment by chessbyte** [comment]
I am trying to understand the context of this PR so we can have it under an issue that someone not well-versed in the technology can get a sense of what this is about.  Should this PR be part of this [issue](https://github.com/ManageIQ/manageiq-pods/issues/415)?

**Comment by carbonin** [comment]
That doesn't answer my question @gyliu513 I'm concerned about keeping these copies up to date with each other as development progresses. I don't think it will hold up this PR, but I want to bring up the suggestion that we maybe move these generator steps to CI (or at least check that running them doesn't change anything).

**Comment by gyliu513** [comment]
@carbonin make sense, I think the CI should cover this. thanks!

**Comment by gyliu513** [comment]
@chessbyte good point, I have updated the description here https://github.com/ManageIQ/manageiq-pods/pull/446#issue-403788021 by referring to issue #415

**Comment by Fryguy** [comment]
I like the idea of having CI verify that the 2 copies match...this will definitely prevent PRs that change one and forget to change the other

**Comment by carbonin** [comment]
Yeah, especially because they are two separate generator commands. Opened https://github.com/ManageIQ/manageiq-pods/issues/448

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 67d0e01ee1021ae5286e64c48b8ad08a125a0ab1
Author: Nick Carboni <ncarboni@redhat.com>
Date:   Wed Apr 15 12:01:18 2020 -0400

    Merge pull request #446 from gyliu513/olm

    Added olm files

    (cherry picked from commit 2dc022d7026a5fe3ca9c09c84dc92d500c992ee0)
```

**Pull request merged**
