### PR TITLE
[FINE] Deploy MIQ using external PG database

### PR DESCRIPTION
**Pull request by simon3z**
Backport to fine branch of #119 and #135 

cc @gtanzillo @bazulay @fbladilo @sdodson @joelddiaz

### CODE REVIEW

**Comment by simon3z** [comment]
@gtanzillo this is a backport for fine. I tested this with @joelddiaz on RDS and it worked for us.

**Comment by carbonin** [comment]
@simaishi Are you handling fine backport PRs for this repo also?

**Comment by simaishi** [comment]
@carbonin yes

**Comment by simaishi** [comment]
@Loicavenel - please ack for Fine/5.8.z.

**Comment by Loicavenel** [comment]
I am fine.

**Comment by simon3z** [comment]
@Loicavenel @simaishi https://bugzilla.redhat.com/show_bug.cgi?id=1474842

**Comment by simon3z** [comment]
@gtanzillo I think this is ready for merge.

**Comment by simaishi** [comment]
@simon3z merging/backporting to Fine branch is for `blocker` PRs only right now.  I'll merge once we start working for the next release.

**Pull request merged**
