### PR TITLE
Set memcached server override in ENV["MEMCACHED_SERVER"] rather than sed

### PR DESCRIPTION
**Pull request by bdunne**
We shouldn't edit settings.yml as it's the default shipping with the product.

### CODE REVIEW

**Comment by carbonin** [comment]
Would this be better as a docker-asset? Or do you want to keep this openshift-ish stuff away from the pure docker stuff?

**Comment by bdunne** [comment]
I think ERB rendering in YAML is disabled in production mode, and I don't want to ship a hard-coded value since the environment variable could change.

**Comment by Fryguy** [comment]
I think it might be better to store it in config/environment/production.yml .  I like to leave settings.local.yml for users.

**Comment by carbonin** [comment]
@bdunne Was there a reason to keep this file in `settings.local.yml` rather than take @Fryguy 's suggestion of `production.local.yml`?

**Comment by bdunne** [comment]
With the changes merged in https://github.com/ManageIQ/manageiq/pull/15326 we can use an ENV variable instead.

**Comment by Fryguy** [comment]
@bdunne Can you change the PR title to reflect the new direction?

**Pull request merged**
