### PR TITLE
Do not use comments in the example CR.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

This is fixing the CR template in code, and make it works if I just follow the README guidance.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #

**Special notes for your reviewer**:

FYI @carbonin

### CODE REVIEW

**Comment by carbonin** [comment]
I'm not really sure how useful this is as a user will almost always need to change something in this file.

Can we maybe just remove it and leave an example in the documentation? My concern is that people are going to deploy this then complain that it doesn't work in whatever environment they're in. Is there a compelling reason to keep it around?

**Comment by gyliu513** [comment]
@carbonin if you take a look at https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml#L5-L50 , you will see the CR was actually used in the CSV file and it has lot of `null` field, and this will be shown on OCP UI as the CR resource for the CSV file, so I was hoping we can add some real value so that customer will know what kind of values should set for each field.

**Comment by carbonin** [comment]
Yeah, I see that now. But I also just opened up https://github.com/ManageIQ/manageiq-pods/pull/451 which will overwrite most of this anyway. Do you want to get this in first and I can rebase on top of these changes or do you think it makes more sense to just wait for #451 to land and close this for now?

**Comment by gyliu513** [comment]
let me close this one and fix this in #451 , thanks @carbonin

**Pull request closed without merging**
