### PR TITLE
added openscap-scanner rpm

### PR DESCRIPTION
**Pull request by bazulay**
resolving issue #79

### CODE REVIEW

**Comment by bazulay** [comment]
@simaishi  @fbladilo

**Comment by fbladilo** [comment]
@bazulay @simaishi Is there anything else needed (configs,etc) besides the RPM  to make the scap scanning work on the appliance?

**Comment by bazulay** [comment]
@fbladilo  only the rpm , this rpm is needed just to analyze the outcome of the scan ... the scan itself is performed from a scanner pod

**Comment by fbladilo** [comment]
@bazulay Cool, LGTM

**Comment by simaishi** [comment]
Euwe backport details:

```
$ git log -1
commit 2f415756834f5a387f25cc631c4e5faca311e362
Author: Franco Bladilo <fbladilo@redhat.com>
Date:   Thu Jan 12 08:59:01 2017 -0600

    Merge pull request #80 from bazulay/missing_openscap_scanner_rpm
    
    added openscap-scanner rpm
    (cherry picked from commit e2ffeecee9d0bff95b09057021c00cfa1e12409f)
```

**Pull request merged**
