### PR TITLE
Typos: Other limit variables use CpuLimit, not Cpulimit.

### PR DESCRIPTION
**Pull request by jrafanie**

### CODE REVIEW

**Comment by Fryguy** [comment]
@bdunne Do we have upgrade concerns with something like this?

**Comment by bdunne** [comment]
> @bdunne Do we have upgrade concerns with something like this?

Yep

**Comment by kbrock** [comment]
This looks still to be the case:
- The yaml uses `kafkaCpulimit`.
- The go code references `kafkaCpuLimit`.
- the go serialization code references `kafkaCpulimit`.

Do we still want this PR to use camel case?

**Comment by jrafanie** [comment]
> This looks still to be the case:
> 
> * The yaml uses `kafkaCpulimit`.
> * The go code references `kafkaCpuLimit`.
> * the go serialization code references `kafkaCpulimit`.
> 
> Do we still want this PR to use camel case?

Preferably we can normalize them to the same convention.  If any change is risky, we can just close this.

**Pull request closed without merging**
