### PR TITLE
Upgrade Go

### PR DESCRIPTION
**Pull request by bdunne**
Upgrade to go 1.20

### CODE REVIEW

**Comment by Fryguy** [comment]
If possible I'd like to delay until https://github.com/golang/go/issues/54385 is released

**Comment by bdunne** [comment]
> If possible I'd like to delay until [golang/go#54385](https://github.com/golang/go/issues/54385) ([GHSA-q856-gh5w-3vwg](https://github.com/advisories/GHSA-q856-gh5w-3vwg)) is released (It might be part of 1.19.2, but hard to tell at the moment)

Why wait?  We can't set a minimum minor version, so we just require 1.19 and the mentioned change appears to be in the 1.19 branch.

**Comment by Fryguy** [comment]
Because our scanners are picking up on that one, and unless it's released, it's like shooting ourselves in the foot.  If it wasn't a critical I wouldn't mind so much.

**Comment by Fryguy** [comment]
Ok, I doubled checked and this was backported in https://github.com/golang/go/commit/2833550 which landed in 1.19.1.  This is good to go, then (pun intended).

P.S. Spelunking go's gerrit and finding the exact commit that made it is such a pain. 😱

**Comment by Fryguy** [comment]
Marking oparin/no because we want to release soon and I don't want to introduce any stability

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `petrosian` in commit 983442ebcbec6077dba158b4509526ace360f748.

```text
commit 983442ebcbec6077dba158b4509526ace360f748
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Feb 16 16:31:00 2023 -0500

    Merge pull request #914 from bdunne/go_1.19
    
    Upgrade Go
    
    (cherry picked from commit e90ed5437cb70cc441e0dbae76d9cce81943d3f2)
```

**Pull request merged**
